### ISSUE TITLE
base10Integer in Chapter 24

### ISSUE THREAD

**Issue by PangLuo** [johnchandlerburnham/hpfp#2]
The design of base10Integer is really nice, but it may cause overflow:

*PositiveInteger> parseString base10Integer mempty "10231234567898766554"
Success (-8215509505810785062)

A slight change as follows fixes the bug:

base10Integer :: Parser Integer
base10Integer = go 0 where
  go acc = do
    d <- parseDigit <?> "integer"
    let acc' = acc * 10 + toInteger (digitToInt d)
    try (go acc') <|> return acc'

**Comment by johnchandlerburnham** [comment]
Thanks for the contribution, and sorry it took me so long to merge this!
